name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  quality-checks:
    name: Pre-publish Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run typecheck || npx tsc --noEmit

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test -- --run 2>/dev/null

      - name: Build library
        run: npm run build

      - name: Check package contents
        run: |
          echo "Package contents:"
          npm pack --dry-run

  publish-npm:
    name: Publish to NPM Registry
    needs: quality-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js with NPM registry
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build
      - name: Configure NPM for publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm whoami || echo "Not authenticated yet"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to NPM
        if: github.event_name == 'release'
        run: |
          # Determine tag from release (beta, alpha, etc.)
          TAG="latest"
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            TAG="next"
          fi

          echo "Publishing with tag: $TAG"
          npm publish --access public --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
